# Site settings
title: Luke Bae
description: "A long time ago in a galaxy far, far away...."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jhbae.github.io"

# User settings
username: Luke Bae
user_title: Iâ€™m your son
email: kroot111@gmail.com
twitter_username: Abraxas5
github_username:  jhbae
gplus_username: 102464230133449888715 
#disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
#permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
#  - title: my posts
#    url: /posts
#  - title: series
#    url: /series
#  - title: tags
#    url: /tags
  - title: About me
    url: /2016/09/20/who-is-luke
# projects in header index
projects:
#  - name: asciilang
#    url: https://github.com/victorvoid/asciilang
#  - name: vim-frontend
#    url: https://github.com/victorvoid/vim-frontend
#  - name: generator-capybara
#    url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
